Repository wecode-bootcamp-korea/33-backend-westagram-1, pull requests merged in 2022-05, with the labels that each got.

#1 [33기 홍길동] Mission 1 : Django 초기 세팅
  students/junho/manage.py
  students/junho/westagram/__init__.py
  students/junho/westagram/asgi.py
  students/junho/westagram/settings.py
  students/junho/westagram/urls.py
  students/junho/westagram/wsgi.py
Labels: 완료

#2 33기 김민정 Misson1 장고초기세팅
  students/minjeong/.gitignore
  students/minjeong/manage.py
  students/minjeong/requirements.txt
  students/minjeong/westagram/__init__.py
  students/minjeong/westagram/asgi.py
  students/minjeong/westagram/settings.py
  students/minjeong/westagram/urls.py
  students/minjeong/westagram/wsgi.py
Labels: 완료

#4 [33기 황재승] Mission 1: Django 초기 세팅
  students/jaeseung/.gitignore
  students/jaeseung/manage.py
  students/jaeseung/requirements.txt
  students/jaeseung/westagram/__init__.py
  students/jaeseung/westagram/asgi.py
  students/jaeseung/westagram/settings.py
  students/jaeseung/westagram/urls.py
  students/jaeseung/westagram/wsgi.py
Labels: 완료

#6 [33기 강세영] Mission 1 : Django 초기 세팅
  students/seyoung/.gitignore
  students/seyoung/manage.py
  students/seyoung/requirements.txt
  students/seyoung/westagram/__init__.py
  students/seyoung/westagram/asgi.py
  students/seyoung/westagram/settings.py
  students/seyoung/westagram/urls.py
  students/seyoung/westagram/wsgi.py
Labels: 완료

#5 33기 김민정 Mission 2: 모델링
  students/minjeong/users/__init__.py
  students/minjeong/users/admin.py
  students/minjeong/users/apps.py
  students/minjeong/users/migrations/0001_initial.py
  students/minjeong/users/migrations/0002_user_delete_signup.py
  students/minjeong/users/migrations/0003_user_created_at_user_updated_at.py
  students/minjeong/users/migrations/0004_alter_user_updated_at.py
  students/minjeong/users/migrations/0005_alter_user_created_at_alter_user_updated_at.py
  students/minjeong/users/migrations/__init__.py
  students/minjeong/users/models.py
  students/minjeong/users/tests.py
  students/minjeong/users/views.py
  students/minjeong/westagram/settings.py
Labels: 멘토 리뷰 요청

#7 [33기 황재승] Mission 2: 모델링
  students/jaeseung/users/__init__.py
  students/jaeseung/users/admin.py
  students/jaeseung/users/apps.py
  students/jaeseung/users/migrations/__init__.py
  students/jaeseung/users/models.py
  students/jaeseung/users/tests.py
  students/jaeseung/users/views.py
Labels: 멘토 리뷰 요청

#8 [33기 강세영] Mission 2: 모델링
  students/seyoung/users/__init__.py
  students/seyoung/users/admin.py
  students/seyoung/users/apps.py
  students/seyoung/users/migrations/0001_initial.py
  students/seyoung/users/migrations/__init__.py
  students/seyoung/users/models.py
  students/seyoung/users/tests.py
  students/seyoung/users/views.py
  students/seyoung/westagram/settings.py
Labels: 완료

#10 [33기 황재승] Makemigrations, migrate 완료
  students/jaeseung/users/migrations/0001_initial.py
  students/jaeseung/users/views.py
  students/jaeseung/westagram/settings.py
Labels: 완료

#14 [33기 정병휘] Mission 1: Django 초기 세팅
  students/byeonghwi/.gitignore
  students/byeonghwi/manage.py
  students/byeonghwi/requirements.txt
  students/byeonghwi/westagram/__init__.py
  students/byeonghwi/westagram/asgi.py
  students/byeonghwi/westagram/settings.py
  students/byeonghwi/westagram/urls.py
  students/byeonghwi/westagram/wsgi.py
Labels: 완료

#12 [33기 강세영] Mission 3: 회원가입 기능 구현
  students/seyoung/users/urls.py
  students/seyoung/users/views.py
  students/seyoung/westagram/settings.py
  students/seyoung/westagram/urls.py
Labels: 완료

#13 [33기 황재승] Mission 3: 회원가입 기능 구현
  students/jaeseung/users/urls.py
  students/jaeseung/users/views.py
  students/jaeseung/westagram/urls.py
Labels: 완료

#11 [33기 김민정] Mission 3: 회원가입 기능 구현
  students/minjeong/users/urls.py
  students/minjeong/users/views.py
  students/minjeong/westagram/urls.py
Labels: 완료

#16 [33기 정병휘] Mission 2: 모델링
  students/byeonghwi/users/__init__.py
  students/byeonghwi/users/admin.py
  students/byeonghwi/users/apps.py
  students/byeonghwi/users/migrations/0001_initial.py
  students/byeonghwi/users/migrations/__init__.py
  students/byeonghwi/users/models.py
  students/byeonghwi/users/tests.py
  students/byeonghwi/users/urls.py
  students/byeonghwi/users/views.py
  students/byeonghwi/westagram/settings.py
Labels: 멘토 리뷰 요청

#17 [33기 황재승] Mission 4: 로그인 기능 구현
  students/jaeseung/users/urls.py
  students/jaeseung/users/views.py
Labels: 완료

#15 [33기 김민정] Mission 4: 로그인 기능 구현
  students/minjeong/users/urls.py
  students/minjeong/users/views.py
  students/minjeong/westagram/urls.py
Labels: 완료

#18 [33기 강세영] Mission 4: 로그인 기능 구현
  students/seyoung/users/urls.py
  students/seyoung/users/views.py
Labels: 멘토 리뷰 요청

#19 [33기 황재승] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jaeseung/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#20 [33기 김민정] Mission 5: 회원가입 비밀번호 암호화 적용 피어 리뷰 요청
  students/minjeong/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#22 [33기 정병휘] Mission 3: 회원가입 기능 구현
  students/byeonghwi/users/urls.py
  students/byeonghwi/users/views.py
  students/byeonghwi/westagram/urls.py
Labels: 완료

#21 [33기 강세영] Mission 5: 회원가입 비밀번호 암호화 적용
  students/seyoung/requirements.txt
  students/seyoung/users/views.py
Labels: 완료

#23 [33기 김민정] Mission 6: 로그인 JWT 발급
  students/minjeong/requirements.txt
  students/minjeong/users/views.py
  students/minjeong/westagram/settings.py
Labels: 완료

#24 [33기 강세영] Mission 6: 로그인 JWT 발급
  students/seyoung/requirements.txt
  students/seyoung/users/views.py
  students/seyoung/westagram/settings.py
Labels: 완료

#25 [33기 황재승] Mission 6: 로그인 JWT 발급
  students/jaeseung/users/views.py
  students/jaeseung/westagram/settings.py
Labels: 완료

#26 [33기 정병휘] Mission 4: 로그인 기능 구현
  students/byeonghwi/users/urls.py
  students/byeonghwi/users/views.py
Labels: 멘토 리뷰 요청
